"""add stock_minimo column to insumo

Revision ID: b482263f7bb0
Revises: 
Create Date: 2025-10-06 08:34:03.585909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b482263f7bb0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insumo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('denominacion', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.String(length=100), nullable=False),
    sa.Column('modelo', sa.String(length=100), nullable=False),
    sa.Column('cantidad_por_caja', sa.Integer(), nullable=False),
    sa.Column('precio_caja', sa.Float(), nullable=False),
    sa.Column('precio_unitario', sa.Float(), nullable=False),
    sa.Column('codigo_barras', sa.String(length=50), nullable=True),
    sa.Column('stock_minimo', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_barras')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('compra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('insumo_id', sa.Integer(), nullable=False),
    sa.Column('cantidad_cajas', sa.Float(), nullable=False),
    sa.Column('precio_caja_compra', sa.Float(), nullable=False),
    sa.Column('proveedor', sa.String(length=100), nullable=True),
    sa.Column('lote', sa.String(length=50), nullable=True),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=True),
    sa.Column('fecha_compra', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['insumo_id'], ['insumo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consumo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('insumo_id', sa.Integer(), nullable=False),
    sa.Column('cantidad_unidades', sa.Float(), nullable=False),
    sa.Column('proyecto', sa.String(length=100), nullable=True),
    sa.Column('observaciones', sa.String(length=200), nullable=True),
    sa.Column('responsable', sa.String(length=100), nullable=False),
    sa.Column('fecha_consumo', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['insumo_id'], ['insumo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('consumo')
    op.drop_table('compra')
    op.drop_table('usuario')
    op.drop_table('insumo')
    # ### end Alembic commands ###
